### ISSUE TITLE
triangle_plot not installed

### ISSUE THREAD

**Issue by rlopezcoto** [zblz/naima#112]
Doing some tests I get the following warning:
WARNING: triangle_plot not installed, corner plot not available [naima.plot]

I pip updated naima and got v.0.6.1, but it seems that is not the same here in github, where I cannot find triangle_plot in the code for the warnings

**Comment by zblz** [comment]
The package "triangle_plot" has changed its name to "corner", so in the master version on github all references have been changed. This has not been released, but will go in 0.7. 

In the meantime, v0.6.1 shoud work if you pip install triangle_plot (whic will install corner as a dependency, IIRC). Alternatively, you can install the master version of naima with ``pip install git+http://github.com/zblz/naima.git#egg=naima`` and pip install corner.

**Comment by zblz** [comment]
I have now added corner as an actual dependency of naima so it is always installed, so this issue should not happen anymore.
