### ISSUE TITLE
Sphinx warnings

### ISSUE THREAD

**Issue by astrofrog** [zblz/naima#128]
There are some Sphinx warnings that are causing the Travis Sphinx build to fail. I'm not sure if the failure is due to:

```
/home/travis/miniconda/envs/test/lib/python2.7/site-packages/matplotlib/font_manager.py:1288: UserWarning: findfont: Font family [u'cursive'] not found. Falling back to Bitstream Vera Sans
  (prop.get_family(), self.defaultFamily[fontext]))
```

or:

```
WARNING: latex_use_parts is deprecated. Use latex_toplevel_sectioning instead.
WARNING: latex_preamble is deprecated. Use latex_elements['preamble'] instead.
```

**Comment by zblz** [comment]
I believe it's the second block, which comes from use of those config options in `astropy_helpers` and was fixed in https://github.com/astropy/astropy-helpers/pull/275

I'll update `astropy_helpers` to fix the build.
