### ISSUE TITLE
Example script

### ISSUE THREAD

**Issue by suvenduat** [zblz/naima#136]
Hi, 
I am trying to model a SED using a single-zone leptonic jet model, with synchrotron, synchrotron self-Compton (SSC) and external Compton (EC) process to extract many model parameters such as R, δ, B, p1, p2, γmin, γmax, γb, N0 and U_BLR etc. Do you have such an example script? 

Thanks,
Suv

**Comment by zblz** [comment]
@suvenduat - There is an example script for the Crab Nebula that includes SSC and EC, but there doppler boosting is not implemented in the code, so such an example for a jet model would not be trivial. I aimed for examples to be simple applications of the models in `naima`, so this might not be a good fit. However, if you can implement the jet model based on current `naima` models, it could be a great start of a new module containing models that go beyond single population emission.
