### ISSUE TITLE
Error in delta functional approximation of Kelner et al PionDecay implementation

### ISSUE THREAD

**Issue by 55hyan** [zblz/naima#155]
Hi, I found something wrong in your core, maybe it is not a big problem, but I want to tell you.

(http://naima.readthedocs.io/en/latest/_modules/naima/radiative.html#PionDecay)

 In this modules, in def _delta_integrand(self, Epi),  you return qpi / np.sqrt(Epi**2 + self._m_pi**2). But in Kelner et al. 2006, in formula(78), it should be qpi / np.sqrt(Epi**2 -self._m_pi**2), you should change the "+" to "-".

**Comment by zblz** [comment]
@55hyan - You are correct, that sign is wrong! Note that this implementation is not the one used in the `PionDecay` class, which uses the Kafexhiu et al. parametrization.

Fixing the sign resulted in a change of 0.06% over the luminosity of a broad spectrum but might be more important when considering the spectral shape at low energies.

Thanks for the report!
