### ISSUE TITLE
Use of - instead of ~ on boolean (uls)

### ISSUE THREAD

**Issue by mireianievas** [zblz/naima#160]
Hi,

Is there any reason why variables such as notul are obtained with the - operator instead of ~ on booleans (data['ul'] for instance). I have identified several places in the code where it is done this way.

I'm using Python 2.7.13 (numpy 1.13) and this makes naima crash or give weird results when plotting the data. I am not sure if this is something happening with recent python versions or if this was introduced in purpose for compatibility (Python 3?)

Cheers
Mireia

**Comment by mireianievas** [comment]
Ok, silly me. I think this was already fixed in github (but not in the release available with pip)

**Comment by zblz** [comment]
Yep, fixed in master but not released. Will make a release soon even if it's only to include this.

**Comment by zblz** [comment]
@mireianievas - thanks for reporting it anyway!
