### ISSUE TITLE
Problem with plotting blobs

### ISSUE THREAD

**Issue by ottavio89-INFN** [zblz/naima#172]
Hi! I have a problem with plotting the metadata blobs, in particular I would like to get the energy of the parent distribution, We, but I get the following error: 
**WARNING: plot_blob failed for $W_e$: only dimensionless scalar quantities can be converted to Python scalars [naima.analysis]**
so I am not able to save this result.

The command that computes the We is:
**We = IC.compute_We(Eemin=1*u.TeV)**

I am also getting it for a code found in the 'examples' page of the package. 

Thanks a lot in advance for the help!

**Comment by ottavio89-INFN** [comment]
Thank you very much for answering me! But I am not sure to understand the meaning...
Is the problem fixed so that I can reinstall naima, or there is some commands I have to add to the script? Please, use simple words, I am very new to this... :)

**Comment by zblz** [comment]
@ottavio89-INFN - The behaviour you reported was clearly a problem with the `naima` package itself. In the PR I linked I have implemented a fix for it. It has already been merged and released as version 0.8.3, so in order to fix the issue you just need to upgrade naima by doing:
```
pip install --upgrade naima
```

**Comment by ottavio89-INFN** [comment]
Thanks a lot, it's all clear!
