### ISSUE TITLE
Python 3.6 and 3.7 support?

### ISSUE THREAD

**Issue by cdeil** [zblz/naima#178]
@zblz - What are the supported Python 3 versions of Naima?

Here I see Python 3.4 and 3.5:

https://github.com/zblz/naima/blob/e4aac9771ddb45576c954660b07ba81870525e82/setup.py#L124
https://naima.readthedocs.io/en/latest/installation.html

Here I see 3.6 packages:
https://anaconda.org/conda-forge/naima/files

In Gammapy, we currently support 2.7, 3.5, 3.6, 3.7.

@bultako - you had a conda install issue on Python 3.7? Probably not a real issue, just the fact that no Python 3.7 conda package was built at https://anaconda.org/conda-forge/naima/files ?

@zblz - Could you please clarify the supported Python versions, and if possible add a Python 3.7 build on conda-forge?

**Comment by zblz** [comment]
Naima is tested on 2.7, 3.6, and 3.7. I'll update the package tags and the installation docs. I'm also fixing the conda-forge build as the feedstock needed rerendering to build the 3.7 package.
