### ISSUE TITLE
Warning from astropy.extern.six import

### ISSUE THREAD

**Issue by cdeil** [zblz/naima#184]
@zblz - In the Gammapy docs build we're now getting this warning, which will become an error in half a year:
```
/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.7/site-packages/astropy/extern/six.py:15: AstropyDeprecationWarning: astropy.extern.six will be removed in 4.0, use the six module directly if it is still needed
```

It originates from your package, which we use for a docs example, here:
https://github.com/zblz/naima/blob/d6a6781d73bf58fd8269e8b0e3b70be22723cd5b/naima/extern/validator.py#L6

Would you be willing to drop Python 2 support for Naima?

Do you have time to do edits in Naima, or to review PRs if we send something?

cc @adonath @registerrier

**Comment by zblz** [comment]
Fixed in #187.
