### ISSUE TITLE
Test fail with new Numpy version

### ISSUE THREAD

**Issue by cdeil** [zblz/naima#185]
@zblz - There's a small issue because Numpy got more strict in recent versions:
https://travis-ci.org/gammapy/gammapy/jobs/566755816#L3931

Could you please fix this?

I'm confused concerning whether the fix is already in master - the line number seems to have changed, the code here looks OK:
https://github.com/zblz/naima/blob/d6a6781d73bf58fd8269e8b0e3b70be22723cd5b/naima/radiative.py#L169

Maybe you just have to cut another release on PyPI to fix this?

**Comment by zblz** [comment]
I've updated the tests to fail on deprecations in #186 and released a new 0.8.4 version. If it doesn't solve this issue, please reopen.
