### ISSUE TITLE
New release, please

### ISSUE THREAD

**Issue by cdeil** [zblz/naima#191]
I think the last released version of Naima (0.8.4) still has this `astropy<4.0` version constraint?

Astropy 4.0 release is coming very soon.

```
ERROR: naima 0.8.4 has requirement astropy<4.0,>=1.0.2, but you'll have astropy 4.0.dev26757 which is incompatible.
```

@zblz - Can you cut a new release?

**Comment by zblz** [comment]
New release of version 0.9.0 drops Python 2 support and therefore the constraint on astropy.

**Comment by cdeil** [comment]
@zblz - Thank you!
