### ISSUE TITLE
The maximum energy of proton in PionDecay model 

### ISSUE THREAD

**Issue by zhenjieW** [zblz/naima#198]
Dear Dr. Victor Zabalza,

I am very interested in the PionDecay model, and i have read the paper(Kafexhiu, E., Aharonian, F., Taylor, A.M., & Vila, G.S. 2014, Physical Review D, 90, 123014.), in this work you combined experimental data on the pp → π0 production below 2 GeV and results from publicly available Monte Carlo codes at higher energies, to parametrize the γ-ray spectrum due to inelastic p–p collisions, spans from the p–p kinematic threshold to 1 PeV proton energy. So, my question is that if we assume the minimum energy of proton is 10 TeV and the maximum energy of proton is 10000 PeV,  whether the model can still applicable in this condition ?

**Comment by zblz** [comment]
Hi @zhenjieW -- The parametrization given in Kafexhiu et al 2014 indeed does not go beyond 1 PeV, and neither does the implementation in naima. You will get either a null contribution for protons with E_p > 1 PeV when not using a lookup table for the computations, or the same contribution as those of 1 PeV when using a lookup table (keyword argument `useLUT` in `naima.models.PionDecay`). There is a prior model that does not go down to the threshold energy by Kelner, Aharonian, and Bugayov (https://arxiv.org/abs/astro-ph/0606058) that has been parametrized in the 0.1-10^5 TeV range, and it behaves more smoothly (even though not necessarily correctly) beyond the top of that range. There is an implementation of this model in naima that you can import as `from naima.radiative import PionDecayKelner06`.
