### ISSUE TITLE
How to consider the upper-limit for Fermi?

### ISSUE THREAD

**Issue by Jongsu020509** [zblz/naima#205]
Hi, thanks for the development of this code!

I'm trying to use the SED fit with both X-ray (2-10keV) and Gamma-ray (Fermi band) band.
Naima can consider the upper-limit.
Also, I know how to set up the upper-limit in the data table.
I need to use Fermi data, which includes two or three points of the upper-limit at least.

I hope to know how Naima consider and compute during the fitting analysis.
Could you explain that?

Best Regards,
Jongsu

**Comment by zblz** [comment]
Hi Jongsu,

What do you mean by "Fermi data, which includes two or three points of the upper-limit at least."? Do you mean that it is a likelihood profile, as opposed to a single upper limit value? Unfortunately naima cannot take those into account, so you would need to compute a single upper limit at a given confidence level and use that in naima.
