### ISSUE TITLE
Sources for observational spectra

### ISSUE THREAD

**Issue by Oliver-Pereira** [zblz/naima#212]
Not really an issue, but a query. Could you please share sources to download the observational spectra such as the .ecsv files used in the examples?

**Comment by zblz** [comment]
The comments in the ecsv files explain how the files were obtained or generated:
- `CrabNebula_spectrum.ecsv`: generated with `gammapy.datasets.load_crab_flux_points()`
- `RXJ1713_HESS_2007.ecsv`: [Aharonian et al. 2011, A&A 531, 1](https://ui.adsabs.harvard.edu/abs/2011A%26A...531C...1A/abstract)
