### ISSUE TITLE
SED of AGN, the parameters

### ISSUE THREAD

**Issue by LL-RL** [zblz/naima#219]
Dear Dr. Victor Zabalza.
When I use naima's MCMC method to fit the SED of AGN, the parameters always do not converge, i.e. last ensemble lnprob: avg: -inf, max: -inf. How can I solve this problem?

**Comment by zblz** [comment]
Hi LL-RL,

If the fitting is resulting in non finite lnprob values it is likely that you should restrict the ranges of the parameters during the fitting to stay within realistic ranges by using the prior functionality. See [the relevant section in the docs](https://naima.readthedocs.io/en/latest/tutorial.html#building-the-model-and-prior-functions) for more information.

**Comment by LL-RL** [comment]
Hi ZBLZ,
Thanks for your reply, I've actually limited the range of parameters I've fitted, but there is still lnprob: avg: -inf.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zblz/naima"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月18日(星期三) 上午6:30
***@***.***&gt;;
抄送:&nbsp;"陆林 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [zblz/naima] SED of AGN, the parameters (Issue #219)





 
Hi LL-RL,
 
If the fitting is resulting in non finite lnprob values it is likely that you should restrict the ranges of the parameters during the fitting to stay within realistic ranges by using the prior functionality. See the relevant section in the docs for more information.
