### ISSUE TITLE
last ensemble lnprob: avg: -inf,

### ISSUE THREAD

**Issue by LL-RL** [zblz/naima#220]
As you can see in the picture, my lnprob is purely at infinity？？？I have tested that my parameter settings are fine.
![e0bb8f9547accd38f778974b53df18b](https://user-images.githubusercontent.com/69756426/168786856-58674461-40dd-451b-a63c-548216aab064.jpg)

**Comment by zblz** [comment]
Hi,

I believe this must be a similar problem to the one mentioned in #219, please follow the suggestions there.

**Comment by LL-RL** [comment]
Dear zbla,
&nbsp;By studying your open source SED fitting tool, I have some questions to ask you.

(1) For what kind of physical cases are the different electron energy spectrum distributions in the tool, i.e. PowerLaw, ExponentialCutoffPowerLaw, BrokenPowerLaw, ExponentialCutoffBrokenPowerLaw and LogParabola given?
Best.
Lu Lin


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zblz/naima"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月18日(星期三) 上午6:31
***@***.***&gt;;
抄送:&nbsp;"陆林 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [zblz/naima] last ensemble lnprob: avg: -inf, (Issue #220)





 
Hi,
 
I believe this must be a similar problem to the one mentioned in #219, please follow the suggestions there.
