### ISSUE TITLE
Inverse Compton Scattering on Anisotropic Photon field

### ISSUE THREAD

**Issue by Lalenthra** [zblz/naima#223]
Dear zblz

I am trying to model a gamma-ray binary system but am having trouble using InverseCompton on an anisotropic field. I want to use a 'star' seed_photon_field as in the example docs, but I am running into a wall with this since it is not in the list of seed photon fields. I get an error with the message "Will not use seed star because it is not CMB, FIR or NIR." 
Do you have any advice on this? I really appreciate any help you can provide.

Kind regards
Lalenthra

**Comment by zblz** [comment]
Hi Lalenthra,

That message will only be returned when the seed photon field passed is a single string. If you are providing a single photon field, your `seed_photon_fields` should be a list with a single list item containing the four parameters for the anisotropic source field. If the above suggestion does not solve your probelm, can you post a minimal, reproducible example?

**Comment by Lalenthra** [comment]
Yes, that solved it. Thank you very much!
