### ISSUE TITLE
Make examples run faster

### ISSUE THREAD

**Issue by cdeil** [zblz/naima#31]
Could you please make the examples run an order of magnitude or two faster?

As a user what I want to get out of the example is some code I can run quickly to see that it works and then to start modifying and running it repeatably to learn what the different knobs do. I don't care about high sampling densities and very accurate parameter estimates.

Also, if you make the examples faster you can run them on travis-ci ... e.g. at the moment this one is broken on my machine because there is no `cPickle` module in Python 3:
```
Traceback (most recent call last):
  File "CrabNebula_function.py", line 70, in <module>
    import cPickle as pickle
ImportError: No module named 'cPickle'
```

**Comment by zblz** [comment]
Examples have been reworked to use `save_run` instead of pickle and are being run on travis on each push.
