### ISSUE TITLE
Seed photon fields

### ISSUE THREAD

**Issue by oanguner** [zblz/naima#74]
Dear Victor, 

Thanks for producing this nice module. I would like to point out something about the seed photon fields definitions for IC model. In the documentation, its mentioned that

CMB  -> T: 2.72 K with the energy density of 0.261 eV / cm^3
NIR -> T: 70 K with the energy density of 0.5 eV / cm^3 
FIR -> T: 5000 K with the energy density of 1.0 eV / cm^3 

while in the code (radiative.py line 315 to 319) itself, these definitions are given by 

CMB  -> T: 2.72 K 
NIR -> T: 5000 K with the energy density of 0.2 eV / cm^3 
FIR -> T: 70 K with the energy density of 0.2 eV / cm^3 

Additionally, can we define a "new seed photon field" with a user-defined temperature and energy density or we can only use these pre-defined photon fields ?

**Comment by zblz** [comment]
The definition for the NIR and FIR where updated to an approximation with GALPROP and in the master version are set to:
```
        Tcmb = 2.72548 * u.K  # 0.00057 K
        Tfir = 30 * u.K
        ufir = 0.5 * u.eV / u.cm ** 3
        Tnir = 3000 * u.K
        unir = 1.0 * u.eV / u.cm ** 3
```
I will have to update the docs to reflect the change in temperature.

In the (inverse Compton docs)[https://naima.readthedocs.org/en/latest/radiative.html#inverse-compton-radiative-model] there is an explanation of how to use an arbitrary seed photon field. For example, if you wanted to use the CMB and a field named `seed1` at 100 K and 2.5 eV/cm3, you would provide the following option to the IC class: `seed_photon_fields=['CMB',['seed1',100*u.K, 2.5*u.eV/u.cm**3]]`. If you add a fourth field to the list (i.e.: `['seed1',100*u.K, 2.5*u.eV/u.cm**3, 135*u.deg]`, anisotropic IC will be applied.

**Comment by zblz** [comment]
Docs fixed in 421b0, closing issue.
