### ISSUE TITLE
Reading particle distribution from ASCII files for radiative models 

### ISSUE THREAD

**Issue by facero** [zblz/naima#96]
Hi,

Thanks for the great work in naima. I started to use it for the interpretation of my FERMI-HESS data and it is really simple to use.
 
Concerning the SED generation with radiative models, the way I understand how the code works is that you need to feed the radiative models with a particle distribution that is a function. This function has certain attributes like amplitude, etc.
I was wondering how difficult it would be to feed the radiative models with a pre-generated particle distribution (e.g. from a particle acceleration code outputting an ASCII file).
It could still be a function but one would need to add the same attributes than the particle_distribution function.
One possible way to do this would be to read the ASCII file, interpolate the data points and create a particle_distribution function based on the interpolated function.

Any thoughts ?

Fabio

**Comment by zblz** [comment]
As you mention, the radiative classes take a function, so you could use an interpolator function over the  pre-generated particle distribution. It would be useful to include a `TableModel` particle distribution class in `naima.models` that does this automatically. 

The ``particle_distribution`` attributes are not strictly necessary for the radiative models, they will just call the function with an particle energy array and use the energy distribution it returns. The attributes are mostly useful as a way to access the distribution parameters and change them without having to re-instantiate the class. In particular, if the particle distribution has no free parameters that can be called (such as a 1D distribution from a particle acceleration/evolution code) you won't need any arguments or attributes for the class.

**Comment by facero** [comment]
Thanks for the info. If I understand this correctly, I could use an interpolator function and this would be transparent for the SED generation ? You don't make any analytical derivatives from the power-law functions for example (when integrating). I will try to work on this and let you know when ready or if I have some more questions.

**Comment by zblz** [comment]
Indeed, the radiative functions do not use any analytical derivatives so
that the particle distribution function can be as general as possible.

2015-11-18 12:28 GMT+01:00 facero <notifications@github.com>:

**Comment by zblz** [comment]
@facero: I gave a shot at building a TableModel class in #99. It is a class that takes an energy array and an array of values and returns the log-space-interpolated value when called. I have tested it to work with the radiative models. Comment there if you think anything is missing for your use-case and we'll try to figure it out.

**Comment by facero** [comment]
I checked out the TableModel that you implemented and it works like a charm for my study case ! thanks. I see that there are option to show the interpolated values with ._values, ._energy. 
Is this the input to the interpolation or the output interpolated values ? (to compare with the input ASCII file to check that the interpolation worked smoothtly).

**Comment by zblz** [comment]
That's where the input arrays are saved. It is not strictly necessary, as I believe they are also saved within the interpolator function (which internally is at ._interplogy). You can see how the interpolation is checked in the unit tests I wrote for the TableModel class in the test_models.py file: https://github.com/zblz/naima/pull/99/files#diff-fe4cff9181a3bd01b9823a9fc3d68246R420
