### ISSUE TITLE
Allow for arbitrary seed photon fields for inverse Compton

### ISSUE THREAD

**Issue by zblz** [zblz/naima#97]

**Comment by zblz** [comment]
To allow things such as SSC.

**Comment by astrolog1986** [comment]
Dear Victor,

Is it already possible to give synchrotron photon field as a seed photon for inverse-Compton (SSC) ?

Thanks

**Comment by zblz** [comment]
@astrolog1986 - no, it's not possible yet. I started working on it in the PR #106, but its far from finished and tested.
